---
- include: users_and_groups.yaml
- include: packages.yaml
- include: system-config.yaml
- include: zfs.yaml
  when: fs_type == "zfs"

# These 2 should go in order
- include: user_gwagner_dotfiles.yaml
- include: user_gwagner_dwm.yaml

# other packages used by the user: gwagner
- include: user_gwagner_automation.yaml
- include: user_gwagner_arch_automation.yaml
- include: user_gwagner_communication.yaml
- include: user_gwagner_steam.yaml
- include: user_gwagner_video.yaml

# Define all cron jobs
- include: cron.yaml
