---
- name: Check if yay is installed
  ansible.builtin.stat:
    path: /usr/bin/yay
  register: yay_status

- name: Install Yay
  command: "{{ item }}"
  with_items:
    - rm -rf /home/gwagner/yay
    - mkdir /home/gwagner/yay
    - git clone https://aur.archlinux.org/yay.git  /home/gwagner/yay
    - /bin/bash -c "cd /home/gwagner/yay && makepkg -si --noconfirm"
  become: yes
  become_user: gwagner
  when: not yay_status.stat.exists

- name: Install system packages
  kewlfft.aur.aur: 
    use: yay
    name: 
      - alacritty
      - autoconf
      - automake
      - bashtop
      - bc
      - bridge-utils
      - cronie
      - dnsmasq
      - firefox
      - flatpak
      - go
      - iotop
      - lshw
      - man
      - mpv
      - nfs-utils
      - piper
      - polybar-dwm-module
      - ranger
      - reflector
      - snapper
      - snapper-gui-git
      - solaar
      - sudo
      - tree
      - unzip
      - upower
      - vim
      - vulkan-radeon
      - vscodium-bin
      - wget
      - xorg-server
      - xorg-xinit
      - xf86-video-amdgpu
      - zsh
  become: yes
  become_user: gwagner

- name: Remove Unused Packages
  community.general.pacman:
    name: 
      - timeshift
    state: absent
    extra_args: --recursive
