---
- name: Check if yay is installed
  ansible.builtin.stat:
    path: /usr/bin/yay
  register: yay_status

- name: Install Yay
  command: "{{ item }}"
  with_items:
    - rm -rf /home/aur_builder/yay
    - mkdir /home/aur_builder/yay
    - git clone https://aur.archlinux.org/yay.git  /home/aur_builder/yay
    - /bin/bash -c "cd /home/aur_builder/yay && makepkg -si --noconfirm"
  become: yes
  become_user: aur_builder
  when: not yay_status.stat.exists

- name: Install system packages
  aur: 
    use: yay
    name: 
      - alacritty
      - autoconf
      - automake
      - bashtop
      - bc
      - bridge-utils
      - cronie
      - dnsmasq
      - firefox
      - iotop
      - libvirt
      - man
      - mpv
      - nfs-utils
      - numlockx
      - polybar-dwm-module
      - qemu-headless
      - ranger
      - solaar
      - sudo
      - unzip
      - upower
      - vim
      - vulkan-radeon
      - virt-manager
      - vscodium
      - wget
      - xorg-server
      - xorg-xinit
      - xf86-video-amdgpu
      - zfsnap
      - zsh
  become: yes
  become_user: aur_builder