---
- name: Check if yay is installed
  ansible.builtin.stat:
    path: /usr/bin/yay
  register: yay_status

- name: Install Yay
  command: "{{ item }}"
  with_items:
    - rm -rf /home/gwagner/yay
    - mkdir /home/gwagner/yay
    - git clone https://aur.archlinux.org/yay.git  /home/gwagner/yay
    - /bin/bash -c "cd /home/gwagner/yay && makepkg -si --noconfirm"
  become: yes
  become_user: gwagner
  when: not yay_status.stat.exists

- name: Install system packages
  kewlfft.aur.aur: 
    use: yay
    name: 
      - alacritty
      - autoconf
      - automake
      - bashtop
      - bc
      - bridge-utils
      - bluez
      - bluez-libs
      - bluez-plugins
      - bluez-utils
      - chrony
      - cronie
      - dnsmasq
      - expac
      - firefox
      - flatpak
      - go
      - hardinfo
      - htop
      - iotop
      - iptables-nft
      - lshw
      - man
      - mpv
      - nfs-utils
      - nmap
      - openrgb-bin
      - piper
      - polybar-dwm-module
      - ranger
      - reflector
      - rsync
      - screenkey
      - snapper
      - snapper-gui-git
      - solaar
      - speedtest-cli
      - sudo
      - tcpdump
      - tree
      - unzip
      - upower
      - vulkan-radeon
      - wget
      - xf86-video-amdgpu
      - xorg-server
      - xorg-xinit
      - xorg-xsetroot
      - xss-lock
      - zip
      - zsh
  become: yes
  become_user: gwagner

- name: Remove Unused Packages
  community.general.pacman:
    name: 
      - timeshift
    state: absent
    extra_args: --recursive

- name: Enable systemd-timesyncd.service
  ansible.builtin.systemd:
    name: systemd-timesyncd.service
    enabled: yes
    state: started 