---
- name: Copy /etc/pacman.conf
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/pacman.conf"
    dest: /etc/pacman.conf
    owner: root
    group: root 

- name: Copy /etc/modules-load.d/v4l2loopback.conf
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/modules-load.d/v4l2loopback.conf"
    dest: /etc/modules-load.d/v4l2loopback.conf
    owner: root
    group: root

- name: Copy /etc/modprobe.d/v4l2loopback.conf
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/modprobe.d/v4l2loopback.conf"
    dest: /etc/modprobe.d/v4l2loopback.conf
    owner: root
    group: root

- name: Copy /etc/pulse/default.pa
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/pulse/default.pa"
    dest: /etc/pulse/default.pa
    owner: root
    group: root

# After we symlink the new pacman.conf, we need to update pacman
- name: Update Pacman
  command: pacman -Sy --noconfirm
