- name: Install Virtualization Packages
  kewlfft.aur.aur: 
    use: yay
    name: 
      - bind
      - libvirt-glib
      - libvirt-python
      - libvirt
      - looking-glass
      - qemu-headless
      - samba
      - swtpm
      - synergy
      - virt-manager
  become: yes
  become_user: gwagner

- name: Remove Unused Virtualization Packages
  community.general.pacman:
    name: 
      - virtualbox
      - virtualbox-host-dkms
    state: absent
    extra_args: --recursive
    