---
- name: Install packages supporting automation
  aur: 
    use: yay
    name: 
      # All used for the automation to build out an automated Arch Install
      - ansible
      - archiso
      - sshpass
      - python-pip
  become: yes
  become_user: gwagner

- name: Install PyVmomi python package
  pip:
    name: PyVmomi