---
- name: Run "pacman -Sy" to get the multilib db
  community.general.pacman:
    update_cache: yes

- name: Install steam and supporting packages
  kewlfft.aur.aur: 
    use: yay
    name: 
      - libcurl-compat
      - steam
  become: yes
  become_user: gwagner