- name: Install qtile packages
  kewlfft.aur.aur: 
    use: yay
    name: 
      - qtile
      - dunst
      - betterlockscreen
      - sddm
      - multicolor-sddm-theme
      - numix-icon-theme-git
      - nerd-fonts-complete
      - ttf-font-awesome
      - nitrogen
      - picom-rounded-corners
      - rofi
      - rofi-calc
  become: yes
  become_user: gwagner