---
- name: Install apps for communication
  kewlfft.aur.aur: 
    use: yay
    name: 
      - discord
      - teams
  become: yes
  become_user: gwagner

- name: Install the Slack
  community.general.flatpak:
    name: com.slack.Slack
    state: present