- name: Is ZFS already installed on the system
  command: "which zpool"
  register: zpool_exists
  ignore_errors: true

- name: Copy ZFS Kernel Module to Pacman Cache
  ansible.builtin.copy:
    src: files/zfs-dkms-2.0.5-1-x86_64.pkg.tar.zst
    dest: /var/cache/pacman/pkg/zfs-dkms-2.0.5-1-x86_64.pkg.tar.zst
    owner: root
    group: root
    mode: '0644'
  when: zpool_exists.failed

- name: Copy ZFS-Utils to Pacman Cache
  ansible.builtin.copy:
    src: files/zfs-utils-2.0.5-1-x86_64.pkg.tar.zst
    dest: /var/cache/pacman/pkg/zfs-utils-2.0.5-1-x86_64.pkg.tar.zst
    owner: root
    group: root
    mode: '0644'
  when: zpool_exists.failed
  
- name: Install the zfs-dkms and zfs-utils package from disk
  community.general.pacman:
    name: 
      - /var/cache/pacman/pkg/zfs-dkms-2.0.5-1-x86_64.pkg.tar.zst
      - /var/cache/pacman/pkg/zfs-utils-2.0.5-1-x86_64.pkg.tar.zst
    state: latest
  when: zpool_exists.failed

- name: Install ZFS packages
  kewlfft.aur.aur: 
    use: yay
    name: 
      - zfsnap
  become: yes
  become_user: gwagner

- name: zfsnap snapshot zroot/data/home
  ansible.builtin.cron:
    name: "zfsnap zroot/data/home"
    minute: "0"
    hour: "*/4"
    job: "zfsnap snapshot -rv -S -a 6w zroot/data/home"

- name: zfsnap destroy zroot/data/home
  ansible.builtin.cron:
    name: "zfsnap destroy zroot/data/home"
    minute: "0"
    hour: "0"
    job: "zfsnap destroy zroot/data/home"

- name: zfsnap snapshot zroot/ROOT/default
  ansible.builtin.cron:
    name: "zfsnap zroot/ROOT/default"
    minute: "15"
    hour: "*/4"
    job: "zfsnap snapshot -rv -S -a 6w zroot/ROOT/default"

- name: zfsnap destroy zroot/ROOT/default
  ansible.builtin.cron:
    name: "zfsnap destroy zroot/ROOT/default"
    minute: "0"
    hour: "0"
    job: "zfsnap destroy zroot/ROOT/default"

- name: zpool scrub zroot
  ansible.builtin.cron:
    name: "zpool scrub zroot"
    minute: "0"
    hour: "0"
    day: "1,15"
    job: "zpool scrub zroot"
