- name: Copy ZFS Kernel Module to Pacman Cache
  ansible.builtin.copy:
    src: files/zfs-dkms-2.0.5-1-x86_64.pkg.tar.zst
    dest: /var/cache/pacman/pkg/zfs-dkms-2.0.5-1-x86_64.pkg.tar.zst
    owner: root
    group: root
    mode: '0644'

- name: Copy ZFS-Utils to Pacman Cache
  ansible.builtin.copy:
    src: files/zfs-utils-2.0.5-1-x86_64.pkg.tar.zst
    dest: /var/cache/pacman/pkg/zfs-utils-2.0.5-1-x86_64.pkg.tar.zst
    owner: root
    group: root
    mode: '0644'
  
- name: Install package bar from file
  community.general.pacman:
    name: 
      - /var/cache/pacman/pkg/zfs-dkms-2.0.5-1-x86_64.pkg.tar.zst
      - /var/cache/pacman/pkg/zfs-utils-2.0.5-1-x86_64.pkg.tar.zst
    state: latest