---
- name: Arch Configure
  hosts: all
  become: yes
  any_errors_fatal: true
  collections:
    - kewlfft.aur
  pre_tasks:
    - include_vars: vault/passwords.yaml
  roles:  
    - role: action_configure
