---
# Local path for creating an ISO and testing
- name: Arch Validation Setup
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  collections:
    - kewlfft.aur
  pre_tasks:
    - include_vars: vault/passwords.yaml
  roles:
    - role: action_create_arch_iso
      when: validation == True and create_image == True

    - role: action_create_vmware_test_vm
      when: validation == True and virtualization_type == "vmware" and recreate == True
      
    - role: action_create_qemu_test_vm
      when: validation == True  and virtualization_type == "qemu" and recreate == True

# Archiso install from bare metal to VM
- name: Arch Install
  hosts: all
  any_errors_fatal: true
  collections:
    - kewlfft.aur
  pre_tasks:
    - include_vars: vault/passwords.yaml
  roles:  
    - role: action_base_install

# Configure installation of Arch Linux after bare-metal install and/or incremental updates
- name: Arch Configure
  hosts: all
  any_errors_fatal: true
  collections:
    - kewlfft.aur
  pre_tasks:
    - include_vars: vault/passwords.yaml
  roles:  
    - role: action_configure

