FROM ff7raven/arch-automation:latest

ARG ID_RSA
ARG VAULT_PASSWORD

RUN echo "$VAULT_PASSWORD" > /vault-password-file
RUN echo "$ID_RSA" > /id_rsa
RUN chmod 600 /vault-password-file && chmod 600 /id_rsa