---
- name: Remove virtual machine from inventory
  community.vmware.vmware_guest:
    validate_certs: false
    hostname: "{{ vmware_host }}"
    username: "{{ vmware_user }}"
    password: "{{ vmware_password }}"
    name: "{{ vmware_name }}"
    state: absent
    force: True
  delegate_to: localhost
  become: false
  throttle: 1

- name: Get stats of local iso
  ansible.builtin.stat:
    path: /tmp/archlinux.iso
    checksum_algorithm: md5
    get_checksum: yes
  register: local_checksum
  delegate_to: localhost
  become: no
  when: create_image == True

- name: Get hash of remote iso
  command: ssh {{ vmware_user }}@{{ vmware_host }} "md5sum {{ vmware_iso_path }} | head -n1 | cut -d \" \" -f1"
  register: remote_checksum
  delegate_to: localhost
  become: no
  when: create_image == True

- name: Copy image to vmware
  command: scp /tmp/archlinux.iso {{ vmware_user }}@{{ vmware_host }}:{{ vmware_iso_path }}
  delegate_to: localhost
  become: no
  when: create_image == True and local_checksum.stat.checksum != remote_checksum.stdout

- name: Add vmware as a host
  add_host:
    hostname: "{{ vmware_host }}"
    ansible_ssh_host: "{{ vmware_host }}"
    ansible_user: "{{ vmware_user }}"
    ansible_ssh_pass: "{{ vmware_password }}"

- name: Does an arch image exist on vmwre
  command: ls {{ vmware_iso_path }}
  delegate_to: "{{ vmware_host }}"
  become: no
  ignore_errors: True
  register: vmware_arch_iso_exists

- ansible.builtin.fail: 
    msg: Arch ISO does not exist on vmware
  delegate_to: localhost
  become: no
  when: vmware_arch_iso_exists.rc != 0

- name: Create a virtual machine on vmware
  community.vmware.vmware_guest:
    validate_certs: false
    hostname: "{{ vmware_host }}"
    username: "{{ vmware_user }}"
    password: "{{ vmware_password }}"
    folder: /vm/
    name: "{{ vmware_name }}"
    state: poweredon
    guest_id: centos64Guest    
    cdrom:
    - controller_number: 0
      unit_number: 0
      state: present
      type: iso
      iso_path: "[FreeNAS-iSCSI] archlinux.iso"
    disk:
    - size_gb: 60
      type: thin
      datastore: FreeNAS-iSCSI
    - size_gb: 60
      type: thin
      datastore: FreeNAS-iSCSI
    hardware:
      boot_firmware: efi
      memory_mb: 16384
      num_cpus: 16
      num_cpu_cores_per_socket: 8
      scsi: paravirtual
    networks:
    - name: Basement-Server
      connect: yes
      mac: "{{ vmware_mac_address }}"
      ip: "{{ vmware_ip_address }}"
      netmask: 255.255.255.0
      device_type: vmxnet3
      type: static
  delegate_to: localhost
  register: deploy_vm
  throttle: 1

- name: Wait for VM to start
  wait_for_connection:
    delay: 10
    timeout: 300
    connect_timeout: 1
