---
- name: Install the efibootmgr package
  command: "arch-chroot /mnt/ pacman --noconfirm -Sy efibootmgr"

- name: Install the UEFI bootloader (bootctl)
  command: arch-chroot /mnt/ bootctl install --esp-path=/boot/

- name: Create /mnt/boot/loader/entries/ directory
  ansible.builtin.file:
    path: /mnt/boot/loader/entries/
    state: directory
    recurse: True

- name: "[ZFS] Copy archlinux bootloader config file"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/archlinux-zfs.conf"
    dest: /mnt/boot/loader/entries/archlinux.conf
  when: fs_type == "zfs"

- name: "[BTRFS] Add the archlinux systemd boot template"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/archlinux-btrfs.j2"
    dest: /mnt/boot/loader/entries/archlinux.conf
  when: fs_type == "btrfs"

# - name: "[BTRFS] Copy archlinux bootloader config file"
#   ansible.builtin.copy:
#     src: "{{ role_path }}/files/archlinux-btrfs.conf"
#     dest: /mnt/boot/loader/entries/archlinux.conf
#   when: fs_type == "btrfs"
