---

- name: Check is pacstrap has already been run
  ansible.builtin.stat:
    path: /mnt/etc
  register: pacstrap_status

- name: Update PGP keys
  command: pacman -Sy --noconfirm archlinux-keyring

- name: Run pacstrap for base system install
  command: pacstrap /mnt/ base linux-lts linux-lts-headers linux-firmware net-tools openssh amd-ucode iwd which python sudo git base-devel go bash btrfs-progs iptables-nft
  when: not pacstrap_status.stat.exists
