---

- name: Check is pacstrap has already been run
  ansible.builtin.stat:
    path: /mnt/etc
  register: pacstrap_status

- name: Find fastest mirrors
  command: reflector --verbose --latest 10 --sort rate --save /etc/pacman.d/mirrorlist
  when: not pacstrap_status.stat.exists

- name: Run pacstrap for base system install
  command: pacstrap /mnt/ base linux-lts linux-lts-headers linux-firmware net-tools openssh amd-ucode iwd which python sudo git base-devel go bash
  when: not pacstrap_status.stat.exists