---
- ansible.builtin.fail: 
    msg: "fs_type is not defined or is not zfs or btrfs"
  when: fs_type is not defined or fs_type != "zfs" and fs_type != "btrfs"

- name: Check the boot environment
  script: 
    cmd: "files/boot_type.sh"
    executable: /bin/bash
  register: boot_environment

- name: Swith UEFI to false if we are on a BIOS system
  set_fact:
    uefi: false
  when: boot_environment.stdout | trim != "UEFI"

- name: Find fastest mirrors
  command: reflector --country "United States" --protocol https --verbose --latest 10 --sort rate --save /etc/pacman.d/mirrorlist

# if there are still problems, this mirror can be used as a local proxy
# Server = http://192.168.8.43:8080/$repo/os/$arch

- include: zfs_archiso.yaml
  when: fs_type == "zfs"

- include: btrfs.yaml
  when: fs_type == "btrfs"

- include: base_install.yaml
- include: generate_fstab.yaml
- include: language.yaml
- include: timezone.yaml
- include: hostname.yaml

- include: zfs/zfs_install.yaml
  when: fs_type == "zfs"

- include: btrfs/btrfs_install.yaml
  when: fs_type == "btrfs"

- include: bootloader.yaml
- include: networking.yaml
- include: ssh.yaml

# Finalize the installation of arch
- include: finalize.yaml
  when: "not skip_finalize"
