# This is a basic workflow to help you get started with Actions

name: Configure

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/configure.yaml'
      - 'roles/action_configure/**'
      - 'arch_configure.yaml'
      - 'inventory.yaml'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/configure.yaml'
      - 'roles/action_configure/**'
      - 'arch_configure.yaml'
      - 'inventory.yaml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, prod-runner]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

       - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: all
          custom_payload: |
            {
              text: `:runner: ${process.env.AS_REPO} | ${process.env.AS_WORKFLOW}`,
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                "fields":[
                    {
                      "title":"Details",
                      "value":`${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REF} by ${process.env.AS_AUTHOR}`,
                      "short":false
                    }
                ]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.

      - name: Build Docker Image
        run: docker build --build-arg VAULT_PASSWORD="${{ secrets.VAULT_PASSWORD }}" --build-arg ID_RSA="${{ secrets.ID_RSA }}" -t arch-automation-ansible:latest -f Dockerfile_Credentials .

      - name: Run the test vmware build
        run: |
          docker run -t --rm \
          -v ${GITHUB_WORKSPACE}:/ansible \
          -w /ansible \
          arch-automation-ansible:latest ansible-playbook -f 10 -i inventory.yaml -l test-btrfs.valewood.lab --vault-password-file /vault-password-file arch_configure.yaml

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: gwagner/arch-automation
          event-type: push-to-public
      
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.